### ISSUE TITLE
feat_extract/MMSA_feat.py --video crashes

### ISSUE THREAD

**Issue by lucaro** [njumagus/MMSF#1]
I'm currently trying to reproduce your work, but I'm experiencing problems when trying to extract the video features.
The stack trace is listed below. Any insights on how to overcome this problem would be appreciated.

```
python feat_extract/MMSA_feat.py --video                                                                                                    
MMSA-FET -                                                                                                                                                                                  
MMSA-FET - ========================== MMSA-FET Started ==========================                                                                                                           MMSA-FET - Temporary directory: feat_extract/MMSA-FET/tmp
MMSA-FET - Log file: 'feat_extract/MMSA-FET/log/MMSA-FET.log'                                                                                                                               MMSA-FET - Config: {'video': {'tool': 'openface', 'fps': 30, 'multiFace': {'enable': True, 'device': 'cuda:0', 'facedetScale': 0.25, 'minTrack': 10, 'numFailedDet': 10, 'minFaceSize': 1, 'cropScale': 0.4}, 'average_over': 1, 'args': {'hogalign': False, 'simalign': False, 'nobadaligned': False, 'landmark_2D': True, 'landmark_3D': True, 'pdmparams': True, 'head_pose': True, 'action_units': True, 'gaze': True, 'tracked': False}}}
MMSA-FET - Initializing OpenFace video feature extractor...
MMSA-FET - Extracting features from 'data/LVU/train/videos/0000.mp4'.
VideoManager is deprecated and will be removed.
`base_timecode` argument is deprecated and has no effect.
MMSA-FET - An Error Occured:
Traceback (most recent call last):
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/main.py", line 314, in run_single
    video_result = self.__video_extract_single(in_file)
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/main.py", line 154, in __video_extract_single
    run_ASD(in_file, self.tmp_dir, fps, self.config['video']['multiFace'])
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/ASD/ASD.py", line 285, in run_ASD
    scores = evaluate_network(files, args)
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/ASD/ASD.py", line 155, in evaluate_network
    audioFeature = python_speech_features.mfcc(audio, 16000, numcep = 13, winlen = 0.025, winstep = 0.010)
  File "/home/user/rossetto/anaconda3/envs/icmr24_reproducibility/lib/python3.8/site-packages/python_speech_features/base.py", line 28, in mfcc
    feat,energy = fbank(signal,samplerate,winlen,winstep,nfilt,nfft,lowfreq,highfreq,preemph,winfunc)
  File "/home/user/rossetto/anaconda3/envs/icmr24_reproducibility/lib/python3.8/site-packages/python_speech_features/base.py", line 54, in fbank
    signal = sigproc.preemphasis(signal,preemph)
  File "/home/user/rossetto/anaconda3/envs/icmr24_reproducibility/lib/python3.8/site-packages/python_speech_features/sigproc.py", line 118, in preemphasis
    return numpy.append(signal[0],signal[1:]-coeff*signal[:-1])
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "feat_extract/MMSA_feat.py", line 200, in <module>
    generate_MMSA_feat(modal='video', modal_tool='openface')
  File "feat_extract/MMSA_feat.py", line 125, in generate_MMSA_feat
    res = fet.run_single(in_file=video_file,text_file=text_file)
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/main.py", line 351, in run_single
    raise e
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/main.py", line 314, in run_single
    video_result = self.__video_extract_single(in_file)
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/main.py", line 154, in __video_extract_single
    run_ASD(in_file, self.tmp_dir, fps, self.config['video']['multiFace'])
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/ASD/ASD.py", line 285, in run_ASD
    scores = evaluate_network(files, args)
  File "/local/scratch/rossetto/icmr24_reproducibility/MMSF/feat_extract/MSA_FET/ASD/ASD.py", line 155, in evaluate_network
    audioFeature = python_speech_features.mfcc(audio, 16000, numcep = 13, winlen = 0.025, winstep = 0.010)
  File "/home/user/rossetto/anaconda3/envs/icmr24_reproducibility/lib/python3.8/site-packages/python_speech_features/base.py", line 28, in mfcc
    feat,energy = fbank(signal,samplerate,winlen,winstep,nfilt,nfft,lowfreq,highfreq,preemph,winfunc)
  File "/home/user/rossetto/anaconda3/envs/icmr24_reproducibility/lib/python3.8/site-packages/python_speech_features/base.py", line 54, in fbank
    signal = sigproc.preemphasis(signal,preemph)
  File "/home/user/rossetto/anaconda3/envs/icmr24_reproducibility/lib/python3.8/site-packages/python_speech_features/sigproc.py", line 118, in preemphasis
    return numpy.append(signal[0],signal[1:]-coeff*signal[:-1])
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by yfraquelle** [comment]
Hi @lucaro, it is hard for me to reproduce this problem but it seems to be an issue with your environment configuration. Did you successfully install "MSA_FET"? You can try our provided Docker image to see if such issues persist.

**Comment by lucaro** [comment]
Yes, MSA_FET ist installed correctly, as far as I can tell.
The problem appears to be that some of the cropped audio files in `MMSF/feat_extract/MMSA-FET/tmp/pycrop` are empty. When they are then read in https://github.com/njumagus/MMSF/blob/eecf4ec93b90fd8557dda4112b43b8ec7f2d8c10/feat_extract/MSA_FET/ASD/ASD.py#L154, an empty array is returned that causes the mfcc to crash. I tried skipping these by adding a check if `audio` is not empty, then it completes the call to `evaluate_network` but crashes in `visualization` due to a mismatch in list length. Is that visualization step actually needed or could it be removed?

**Comment by lucaro** [comment]
I was able to resolve that particular issue by replacing the line with 
```python
audioFeature = python_speech_features.mfcc(audio, 16000, numcep = 13, winlen = 0.025, winstep = 0.010) if len(audio) > 0 else numpy.array([[]])
```

**Comment by yfraquelle** [comment]
It seems that errors exist in ffmpeg commands of `crop_video`. Perhaps you could attempt executing the commands manually in the terminal to ensure their successful execution.

> Yes, MSA_FET ist installed correctly, as far as I can tell. The problem appears to be that some of the cropped audio files in `MMSF/feat_extract/MMSA-FET/tmp/pycrop` are empty. When they are then read in
> 
> https://github.com/njumagus/MMSF/blob/eecf4ec93b90fd8557dda4112b43b8ec7f2d8c10/feat_extract/MSA_FET/ASD/ASD.py#L154
> 
> , an empty array is returned that causes the mfcc to crash. I tried skipping these by adding a check if `audio` is not empty, then it completes the call to `evaluate_network` but crashes in `visualization` due to a mismatch in list length. Is that visualization step actually needed or could it be removed?

**Comment by lucaro** [comment]
The change above appears to have resolved the issue despite the strange ffmpeg behavior.
